import Head from 'next/head'
import Image from 'next/image'
import { Source_Sans_Pro } from '@next/font/google'

import Tweet from './tweet'
import { useState, useEffect } from 'react'
import { useTheme } from 'next-themes'


const sans = Source_Sans_Pro({ 
  weight: '400', 
  subsets: ['latin'] 
})
  

export default function Home() {
  const [isToggleOn, setIsToggleOn] = useState(true)
  const [mounted, setMounted] = useState(false)
  const {theme, setTheme} = useTheme()

  useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted) {
    return null
  }

  function handleClick() {
    setIsToggleOn(prevState => !prevState)
    isToggleOn ? setTheme('light') : setTheme('dark')
  }

  return (
    <>
      <Head>
        <title>Twitter Embed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen w-screen p-10 bg-blue-200/70 dark:bg-darkblue-500'>
        
        <div className='flex'>
          <button onClick={handleClick}>
            {isToggleOn ? 
              <Image
                src='/sun.png'
                alt='light button'
                width={30}
                height={100}
              /> 
            : 
              <Image
                src='/moon.png'
                alt='dark button'
                width={30}
                height={100}
              />
          }
          </button>
        </div>

        <div className='relative w-[600px] h-[250px] bg-white dark:bg-darkblue-400 mx-auto top-44 shadow-blue-300 drop-shadow-2xl'>
          <div className='flex pt-9 px-8'>
            <Image
              src='/pfp.jpg'
              alt='Profile Pictures'
              width={60}
              height={100}
              className='rounded-full' 
            />
            <div className='ml-5 my-auto flex-row'>
              <p className='font-bold text-black dark:text-white'>Freddy Kudlacik</p>
              <p className='font-light text-black/70 dark:text-white/70'>@FreddyKudlacik</p>
            </div>
            <Image
              src='/twitter.svg'
              alt='Twitter icon'
              width={30}
              height={100}
              className='ml-auto'
            />
          </div>
          <div className={`${sans.className} w-11/12 pl-8 mt-4 text-black dark:text-white`}>
            <Tweet>Why was the JavaScript developer sad? Because they didn't know how to 'null' their feelings. #programming #code</Tweet>
          </div>
          <div className='flex w-6/12 pl-8 mt-4'>
            <Image
              src={theme === 'light' ? '/heart.svg' : '/heart-white.svg'}
              alt='heart icon'
              width={20}
              height={100} 
            />
            <p className={`${sans.className} text-black/60 dark:text-white/60 pl-2`}>650</p>
            <p className={`${sans.className} text-black/60 dark:text-white/60 pl-2 font-semibold`}>3:40 PM – Feb 24, 2022</p>
          </div>
        </div>
      </main>
    </>
  )
}
